/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    members: Member;
    events: Event;
    records: Record;
    posts: Post;
    pages: Page;
    'join-submissions': JoinSubmission;
    redirects: Redirect;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    records: RecordsSelect<false> | RecordsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'join-submissions': JoinSubmissionsSelect<false> | JoinSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'ai-service';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * 迁移追踪信息；新内容可留空。
   */
  source?: {
    notionPageId?: string | null;
    notionLastEditedAt?: string | null;
    checksum?: string | null;
    lastSyncedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  title: string;
  avatar?: (number | null) | Media;
  role: string;
  city?: string | null;
  focusAreas?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  headline?: string | null;
  bio: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  quote?: string | null;
  joinedAt?: string | null;
  featured?: boolean | null;
  verified?: boolean | null;
  socials?: {
    website?: string | null;
    github?: string | null;
    x?: string | null;
    linkedin?: string | null;
    xiaohongshu?: string | null;
  };
  /**
   * 公开 URL 的稳定标识。为空时由标题生成。
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * 迁移追踪信息；新内容可留空。
   */
  source?: {
    notionPageId?: string | null;
    notionLastEditedAt?: string | null;
    checksum?: string | null;
    lastSyncedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 从草稿、预览到发布，管理 IGNAI 的真实活动。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  excerpt: string;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  startAt: string;
  endAt?: string | null;
  location: string;
  format: 'offline' | 'online' | 'hybrid';
  registrationURL?: string | null;
  organizers?: (number | Member)[] | null;
  participants?: (number | Member)[] | null;
  /**
   * 公开 URL 的稳定标识。为空时由标题生成。
   */
  slug: string;
  featured?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * 迁移追踪信息；新内容可留空。
   */
  source?: {
    notionPageId?: string | null;
    notionLastEditedAt?: string | null;
    checksum?: string | null;
    lastSyncedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "records".
 */
export interface Record {
  id: number;
  title: string;
  excerpt: string;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  recordType: 'recap' | 'story' | 'resource' | 'project';
  timelineDate?: string | null;
  timelineEndDate?: string | null;
  dateStatus: 'confirmed' | 'approximate' | 'unknown';
  location?: string | null;
  events?: (number | Event)[] | null;
  members?: (number | Member)[] | null;
  gallery?: (number | Media)[] | null;
  outcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * 公开 URL 的稳定标识。为空时由标题生成。
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * 迁移追踪信息；新内容可留空。
   */
  source?: {
    notionPageId?: string | null;
    notionLastEditedAt?: string | null;
    checksum?: string | null;
    lastSyncedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt: string;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authors: (number | Member)[];
  events?: (number | Event)[] | null;
  records?: (number | Record)[] | null;
  categories?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  featured?: boolean | null;
  /**
   * 公开 URL 的稳定标识。为空时由标题生成。
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * 迁移追踪信息；新内容可留空。
   */
  source?: {
    notionPageId?: string | null;
    notionLastEditedAt?: string | null;
    checksum?: string | null;
    lastSyncedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  excerpt?: string | null;
  layout: (
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        action: {
          label: string;
          href: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        heading: string;
        collection: 'members' | 'events' | 'records' | 'posts';
        limit: number;
        featuredOnly?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'communityCollection';
      }
  )[];
  /**
   * 公开 URL 的稳定标识。为空时由标题生成。
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * 迁移追踪信息；新内容可留空。
   */
  source?: {
    notionPageId?: string | null;
    notionLastEditedAt?: string | null;
    checksum?: string | null;
    lastSyncedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 申请内容永不公开读取；公开提交入口仍需在 Route Handler 层增加限流与幂等保护。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-submissions".
 */
export interface JoinSubmission {
  id: number;
  name: string;
  contact: string;
  role: string;
  interests?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  message: string;
  source: string;
  status: 'submitted' | 'reviewing' | 'contacted' | 'accepted' | 'waitlisted' | 'withdrawn' | 'spam' | 'archived';
  profileDraft?: {
    avatar?: (number | null) | Media;
    headline?: string | null;
    website?: string | null;
    github?: string | null;
    xiaohongshu?: string | null;
  };
  review?: {
    assignee?: (number | null) | User;
    notes?: string | null;
    contactedAt?: string | null;
  };
  dedupeKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * 必须是站内绝对路径，例如 /old-path。
   */
  from: string;
  /**
   * 站内路径或完整外部 URL。
   */
  to: string;
  statusCode: '301' | '302' | '307' | '308';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  events?: {
    /**
     * Allow clients to find events.
     */
    find?: boolean | null;
  };
  members?: {
    /**
     * Allow clients to find members.
     */
    find?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
  };
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
  };
  records?: {
    /**
     * Allow clients to find records.
     */
    find?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'records';
        value: number | Record;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'join-submissions';
        value: number | JoinSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  source?:
    | T
    | {
        notionPageId?: T;
        notionLastEditedAt?: T;
        checksum?: T;
        lastSyncedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  title?: T;
  avatar?: T;
  role?: T;
  city?: T;
  focusAreas?:
    | T
    | {
        label?: T;
        id?: T;
      };
  headline?: T;
  bio?: T;
  quote?: T;
  joinedAt?: T;
  featured?: T;
  verified?: T;
  socials?:
    | T
    | {
        website?: T;
        github?: T;
        x?: T;
        linkedin?: T;
        xiaohongshu?: T;
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  source?:
    | T
    | {
        notionPageId?: T;
        notionLastEditedAt?: T;
        checksum?: T;
        lastSyncedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  startAt?: T;
  endAt?: T;
  location?: T;
  format?: T;
  registrationURL?: T;
  organizers?: T;
  participants?: T;
  slug?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  source?:
    | T
    | {
        notionPageId?: T;
        notionLastEditedAt?: T;
        checksum?: T;
        lastSyncedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "records_select".
 */
export interface RecordsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  recordType?: T;
  timelineDate?: T;
  timelineEndDate?: T;
  dateStatus?: T;
  location?: T;
  events?: T;
  members?: T;
  gallery?: T;
  outcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  featured?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  source?:
    | T
    | {
        notionPageId?: T;
        notionLastEditedAt?: T;
        checksum?: T;
        lastSyncedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  authors?: T;
  events?: T;
  records?: T;
  categories?:
    | T
    | {
        label?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  publishedAt?: T;
  featured?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  source?:
    | T
    | {
        notionPageId?: T;
        notionLastEditedAt?: T;
        checksum?: T;
        lastSyncedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              action?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        communityCollection?:
          | T
          | {
              heading?: T;
              collection?: T;
              limit?: T;
              featuredOnly?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  source?:
    | T
    | {
        notionPageId?: T;
        notionLastEditedAt?: T;
        checksum?: T;
        lastSyncedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "join-submissions_select".
 */
export interface JoinSubmissionsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  role?: T;
  interests?:
    | T
    | {
        label?: T;
        id?: T;
      };
  message?: T;
  source?: T;
  status?: T;
  profileDraft?:
    | T
    | {
        avatar?: T;
        headline?: T;
        website?: T;
        github?: T;
        xiaohongshu?: T;
      };
  review?:
    | T
    | {
        assignee?: T;
        notes?: T;
        contactedAt?: T;
      };
  dedupeKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  events?:
    | T
    | {
        find?: T;
      };
  members?:
    | T
    | {
        find?: T;
      };
  pages?:
    | T
    | {
        find?: T;
      };
  posts?:
    | T
    | {
        find?: T;
      };
  records?:
    | T
    | {
        find?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 品牌文字、导航和首页主行动。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  heroStatement: string;
  intro: string;
  primaryCTA: {
    label: string;
    href: string;
  };
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  defaultSEO: {
    title: string;
    description: string;
    image?: (number | null) | Media;
  };
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  heroStatement?: T;
  intro?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        href?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  defaultSEO?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'members';
          value: number | Member;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'records';
          value: number | Record;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}